// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_ChartDraw_FlexComponents_2_H
#define WINRT_ChartDraw_FlexComponents_2_H
#include "winrt/impl/ChartDraw_FlexComponents.1.h"
WINRT_EXPORT namespace winrt::ChartDraw_FlexComponents
{
    struct __declspec(empty_bases) Class : winrt::ChartDraw_FlexComponents::IClass
    {
        Class(std::nullptr_t) noexcept {}
        Class(void* ptr, take_ownership_from_abi_t) noexcept : winrt::ChartDraw_FlexComponents::IClass(ptr, take_ownership_from_abi) {}
        Class();
    };
}
#endif
