// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

void* winrt_make_ChartDraw_FlexComponents_Class()
{
    return winrt::detach_abi(winrt::make<winrt::ChartDraw_FlexComponents::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::ChartDraw_FlexComponents
{
    Class::Class() :
        Class(make<ChartDraw_FlexComponents::implementation::Class>())
    {
    }
}
